source("data_load.R")
png("plot4.png",width=480,height=480,units="px")
par(mfrow = c(2,2))
with(data,{
  plot(Date_and_Time, Global_active_power, type = "l", xlab="", ylab="Global Active Power")
  plot(Date_and_Time, Voltage, type = "l", xlab="datetime")
  plot(Date_and_Time, Sub_metering_1, col = "black", type = "l", xlab="", ylab="Energy sub metering")
  lines(Date_and_Time, Sub_metering_2, col = "red", type = "l", xlab="", ylab="Energy sub metering")
  lines(Date_and_Time, Sub_metering_3, col = "blue", type = "l", xlab="", ylab="Energy sub metering")
  legend("topright", bty="n", lty=1, col = c("black","red","blue"), legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
  plot(Date_and_Time, Global_reactive_power, type = "l", xlab="datetime")
})
dev.off()
